name: Ghost-Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          name: Ghost-Termux-APK
          path: app/build/outputs/apk/debug/*.apk
          
